---
- Alakdan:
    Race: the TÄ“
    Secrets:
    - Luck: Once per session, you may declare something almost unbelievably co-incidental or lucky that happens to your benefit.
    - Command: Once per session an NPC will follow any non-suicidal command you give.
    Keys:
    - Subservient: Hit this key when you act on another's orders.
    - Team Spirit: Hit this key when you act in the team's interest.
    - Tinkerer: Hit this key when you modify, improve, or patch some tech.
    Traits:
    - Many Claws Make Light Work:
        Tags:
        - Mechanic
        - Electrician
        - Handy-Scorpion
        - Improvised Weapons
        - Hacking
        - Tricorder
    - Medic:
        Tags:
        - Field Dressing
        - Bio Knowledge
        - Strong Stomach
        - Pressure Points
        - Surgery
    - Silver Tongue:
        Tags:
        - Raconteur
        - Deceit
        - Bartering
        - Pushing Buttons
        - Sway

- Alessandro Massino:
    Race: the Humans
    Secrets:
    - MacGuiver: Once per session you may automatically produce a plot relevant device from available materials.
    - Outer Self: Once per sessin you can summon an alterate self with a dice pool of six in any one thing.
    Keys:
      - Home: You want little more than to return to Earth. Hit this key when you do something that brings you closer to returning home. Break this key if you pass up a chance to return, or consign yourself to never returning.
      - Humanity: Jonah Palethorpe may have flung you across the universe, but he is the only other human for (as far as you know) thousands of lightyears. Hit this key when you act against your own interests to help or protect another human being.
      - Pursuit of Knowledge: Hit this key when you allow your curiousity to get the better of you and act put yourself in danger or act against your own interests in the pursuit of knowldge.
    Traits:
    - Science:
        Tags:
        - Employ Device
        - Analyze
        - Investigate
        - Reverse Engineer
        - Fabricate
        - Theory
        - Physics
    - Field Medic:
        Tags:
        - Medicine
        - Healing
        - Surgery
        - Sedatives
    - Conscript:
        Tags:
        - Shooting
        - Tactics
        - Hand-to-Hand
        - Self-Defence

- Cuatzanixli (Ili):
    Race: the Nomhuatl
    Secrets:
    - Contacts: Ronseal
    - Blink: You may teleport to anywhere you can see.
    Keys:
    - Guilt: Hit when acting to defend those you were once opposed to.
    - Exposure: Hit this key when you act to remove colonies from the Sender's grasp.
    - No Witnesses: Hit this key when you ensure no-one is left behind to witness your actions.
    Traits:
    - Nomhuatl:
        Tags:
        - Shapeshifter
        - Adaptable
        - Nimble
        - Silent
    - Police - The Gun:
        Tags:
        - Marksmanship
        - Swordsmanship
        - Disarm
        - Improvised Weapon
        - He Fell Down The Stairs
    - Police - The Rest:
        Tags:
        - Negotiate
        - Royal Warships
        - Connections
        - Investigate
        - Part of a Team
        - Access Codes

- Grei:
    Race: The Xaa
    Secrets:
    - Throwing: Anything is a dangerous missile in your hands.
    - Time: Once per session you can retroactively have reacted to something in the last minute.
    Keys:
    - Daredevil: You thrive in dangerous situations. Hit this key when you do something cool that is risky and reckless (especially piloting stunts).
    - Imposter: You are in disguise, passing yourself off as not a person regarded as dangerous by the Monarchy. Hit your key when you perform well enough to fool someone with your disguise.
    - Fraternity: Hit this key when your character is influenced by them or when you show how deep your bond is.
    Traits:
    - Taker:
        Tags:
        - Explosives
        - Sabotage
        - Gain Trust
        - Awareness
        - Threats
        - Thrown Weapons
    - Wayfarer:
        Tags:
        - Navigation
        - Morphology
        - Geographical Awareness
        - Wireless/Comms
        - Tricky Flying
    - Xaa:
        Tags:
        - Rough Skin
        - Electrical Sensitivity
        - Misanthrope
        - Strong

- Jonah Palethorpe:
    Race: the Humans
    Secrets:
    - Nondescript: When you blend into the background, people will not notice you unless you give them a reason to.
    - Technopath: Once per session a machine (including A.I.s) will do what you want.
    Keys:
    - Cuckoo: Hit this key when accepted unknowingly into a community to which you do not belong.
    - New Frontier: Hit this key when you serve the Earth and Britain.
    - Only Way Home: Hit this key when you act to protect Alessandro Massino.
    Traits:
    - Rough Work:
        Tags:
        - Shooting
        - Stabbing
        - Murder
        - Marksman
        - From The Shadows
        - Unfazed
    - Gentleman Spy:
        Tags:
        - Fast Talk
        - Cover Story
        - Blending In
        - Bluster
        - Light-Fingered
        - Quick Exit
    - A Life Of Privilege:
        Tags:
        - Balliol College
        - Theoretical Physics
        - Advanced Mathematics

- Kinoumenon Kinei:
    Race: The Senders
    Secrets:
    - Name: You are infamous. People may not know your face, but when they hear your name they stop in awe.
    - Nigh Invulnerable: Once per session, when you would otherwise mark a condition, you can choose not to do so.
    Keys:
    - Daredevil: You thrive in dangerous situations. Hit this key when you do something cool that is risky and reckless (especially piloting stunts).
    - Rival: You hate someone. Hit this key when you outperform or outfox them in any particular area.
    - Rebel: The Empire is your greatest foe. Hit this   key whenever you strike a blow against them or kill an Imperial agent.
    Traits:
    - Sender:
        Tags:
        - Telepath
        - Telekinetic
        - Metal
        - Internal Compass
    - Underground Criminal:
        Tags:
        - Stealth
        - Scavenger
        - Joyrider
        - Explosions
    - Brawl:
        Tags:
        - Alert
        - Unpredictable
        - Stab
        - Shoot
    - Youth:
        Tags:
        - Sweet-talker
        - Innocent Face
        - Deceit
